import 'package:alaraf/service/strings.dart';
import 'package:flutter/material.dart';

enum Language { arabic, english, turkish }

class TranslateService extends ChangeNotifier {
  var selectedLanguage = Language.english;
  var selectedLanguageValue = {};

  TranslateService() {
    selectedLanguageValue = enKeys;
    notifyListeners();
  }

  goArabic() {
    selectedLanguageValue = arKeys;
    selectedLanguage = Language.arabic;
    notifyListeners();
  }
  goEnglish() {
    selectedLanguageValue = enKeys;
    selectedLanguage = Language.english;
    notifyListeners();
  }
}

var enKeys = {
  StringKeys.str_register: "Register",
  StringKeys.str_update: "Update",
  StringKeys.str_done: "Done",
  StringKeys.str_ability: "Change Your Ability",
  StringKeys.str_price: "Enter Your Price",
  StringKeys.str_remember: "Remember Me",
  StringKeys.str_support: "Send Support Mail",
  StringKeys.str_country: "Country",
  StringKeys.str_sign_in: "Sign In",
  StringKeys.str_buy_gold: "Buy Gold",
  StringKeys.str_profile: "Profile",
  StringKeys.str_sign_out: "Sign Out",
  StringKeys.str_login: "Login",
  StringKeys.str_name: "Name",
  StringKeys.str_mail: "Mail",
  StringKeys.str_password: "Password",
  StringKeys.str_password_conf: "Confirm Passowrd",
  StringKeys.str_coin: "Points",
  StringKeys.str_setting: "Setting",
  StringKeys.str_service: "Services",
  StringKeys.str_cup: "The Cup",
  StringKeys.str_constellations: "Constellation",
  StringKeys.str_hand: "Palmistry",
  StringKeys.str_tarot: "Tarot",
  StringKeys.str_dreams: "Dreams",
  StringKeys.str_face: "Face",
  StringKeys.str_love: "Love Harmony",
  StringKeys.str_spiritual: "My Soul Revealed",
  StringKeys.str_back: "Back",
  StringKeys.str_cup_photo: "Upload a Photo of the cup",
  StringKeys.str_forename: "Forename",
  StringKeys.str_date_of_birth: "Date of Birth",
  StringKeys.str_male: "Male",
  StringKeys.str_female: "Female",
  StringKeys.str_social_situation: "Social Situation",
  StringKeys.str_unmarried: "Unmarried",
  StringKeys.str_married: "Married",
  StringKeys.str_single: "Single",
  StringKeys.str_divorced: "Divorced",
  StringKeys.str_widower: "Widower",
  StringKeys.str_separated: "Separated",
  StringKeys.str_linked: "Linked",
  StringKeys.str_sex: "Sex",
  StringKeys.str_written_letter: "The Written Letter",
  StringKeys.str_voice_message: "Voice Message",
  StringKeys.str_birth_place: "Place of Birth",
  StringKeys.str_fortune_teller: "Fortune Teller",
  StringKeys.str_palmistry: "Palmistry",
  StringKeys.str_download_surah: "Download Surah Al-Kahf",
  StringKeys.str_mothers_name: "Mother's Name",
  StringKeys.str_partners_name: "Partner's Name",
  StringKeys.str_partners_mothers_name: "The Partner's Mother's Name",
  StringKeys.str_partners_birth_date: "Partner's Birth Date",
  StringKeys.str_birth_hour: "Birth Hour",
  StringKeys.str_dashboard: "Dashboard",
  StringKeys.str_profile_personally: "Profile Personally",
  StringKeys.str_portfolio: "Portfolio",
  StringKeys.str_experts: "Experts",
  StringKeys.str_message: "Message",
  StringKeys.str_statistics: "Statistics",
  StringKeys.str_about_expert: "About Expert",
  StringKeys.str_comment: "Comments",
  StringKeys.str_evaluation: "Evaluation",
  StringKeys.str_the_service: "Service",
  StringKeys.str_excellent: "Excellent",
  StringKeys.str_name_of_expert: "Name of The Expert",
  StringKeys.str_voice_of_expert: "Voice of The Expert",
  StringKeys.str_wrong_pass_or_username: "Wrong password or username.",
  StringKeys.str_send: "Send",
  StringKeys.str_not_match: "Passwords do not match",
  StringKeys.str_reply: "Reply",
  StringKeys.str_new: "New",
  StringKeys.str_fortune: "Fortune Telling",
  StringKeys.str_img: "Image",
  StringKeys.str_response: "Response",
  StringKeys.str_read: "Read",
  StringKeys.str_mobile: "Mobile Phone Number",
  StringKeys.str_offline: "Offline",
  StringKeys.str_online: "Online",
  StringKeys.str_busy: "Busy",
  StringKeys.str_away: "Away",
  StringKeys.str_voice_response: "Voice Response",
  StringKeys.str_live_call: "Live\nCall",
  StringKeys.str_voice_info: "Do you want to finish recording or pause?",
  StringKeys.str_voice_pause: "Pause",
  StringKeys.str_voice_stop: "Stop",
  StringKeys.str_not_selected_image: "You need to select last one image!",
  StringKeys.str_required_forename: "Forename required!",
  StringKeys.str_required_birt_place: "Birth Place required!",
  StringKeys.str_required_sex: "Sex information required!",
  StringKeys.str_required_social: "Social Situation information required!",
  StringKeys.str_required_birth_date: "Birth date required!",
  StringKeys.str_required_voice: "Voice record required!",
  StringKeys.str_required_mother_name: "Mother name required!",
  StringKeys.str_notify_me: "Notify me",
  StringKeys.str_not_notify: "Dont notify me",
  StringKeys.str_call_expert: "Call Expert",
  StringKeys.str_incoming_call: "Incoming call",
  StringKeys.str_answered: "Answered",
  StringKeys.str_not_answered: "Not Answered",
  StringKeys.str_rejected: "Rejected",
  StringKeys.str_waiting: "Waiting",

};
var arKeys = {
  StringKeys.str_update: "تحديث",
  StringKeys.str_done: "منجز",
  StringKeys.str_remember: "تذكرنى",
  StringKeys.str_support: "إرسال بريد الدعم",
  StringKeys.str_register: "تسجيل",
  StringKeys.str_sign_in: "تسجيل الدخول",
  StringKeys.str_sign_out: "تسجيل الخروج",
  StringKeys.str_login: "تسجيل الدخول",
  StringKeys.str_name: "اسم",
  StringKeys.str_mail: "بريد",
  StringKeys.str_password: "كلمه السر",
  StringKeys.str_password_conf: "تأكيد كلمة المرور",
  StringKeys.str_coin: "عدد النقاط",
  StringKeys.str_setting: "ضبط",
  StringKeys.str_service: "الخدمات",
  StringKeys.str_cup: "الفنجان",
  StringKeys.str_hand: "الكف",
  StringKeys.str_tarot: "التاروت",
  StringKeys.str_dreams: "الاحلام",
  StringKeys.str_face: "الوجه",
  StringKeys.str_love: "توافق حب",
  StringKeys.str_spiritual: "كشف روحي",
  StringKeys.str_back: "رجوع",
  StringKeys.str_cup_photo: "تحميل صورة الفنجان",
  StringKeys.str_forename: "الاسم الأول",
  StringKeys.str_date_of_birth: "تاريخ الميلاد",
  StringKeys.str_male: "ذكر",
  StringKeys.str_female: "انثى",
  StringKeys.str_social_situation: "الوضع الاجتماعي",
  StringKeys.str_unmarried: "أعزب",
  StringKeys.str_married: "متأهل",
  StringKeys.str_single: "غير مرتبطة",
  StringKeys.str_divorced: "مطلقة",
  StringKeys.str_widower: "أرمل",
  StringKeys.str_separated: "فصل",
  StringKeys.str_linked: "مرتبط",
  StringKeys.str_sex: "الجنس",
  StringKeys.str_written_letter: "الرسالة الخطية",
  StringKeys.str_voice_message: "الرسالة الصوتية",
  StringKeys.str_constellations: "الابرج",
  StringKeys.str_birth_place: "مكان الولادة",
  StringKeys.str_palmistry: "الكف",
  StringKeys.str_download_surah: "تحميل صورة الكف",
  StringKeys.str_fortune_teller: "اختر عالم الفلك",
  StringKeys.str_mothers_name: "اسم الام",
  StringKeys.str_partners_name: "اسم الشريك",
  StringKeys.str_partners_mothers_name: "اسم ام الشريك",
  StringKeys.str_partners_birth_date: "تاريخ ميلاد الشريك",
  StringKeys.str_birth_hour: "ساعة الولادة",
  StringKeys.str_dashboard: "لوحة المعلومات",
  StringKeys.str_profile_personally: "الملف الشخصي",
  StringKeys.str_portfolio: "المحفظة",
  StringKeys.str_experts: "الخبراء",
  StringKeys.str_message: "الرسائل",
  StringKeys.str_statistics: "الإحصائيات",
  StringKeys.str_about_expert: "عن الخبير",
  StringKeys.str_comment: "التعليقات",
  StringKeys.str_evaluation: "التقييم",
  StringKeys.str_the_service: "الخدمة",
  StringKeys.str_excellent: "ممتاز",
  StringKeys.str_name_of_expert: "اسم الخبير",
  StringKeys.str_voice_of_expert: "رسالة صوتية من الخبير",
  StringKeys.str_wrong_pass_or_username:"اسم مستخدم أو كلمة مرور خاطئة",
  StringKeys.str_send: "إرسال",
  StringKeys.str_not_match: "كلمة المرور غير مطابقة",
  StringKeys.str_reply: "إجابة",
  StringKeys.str_new: "جديد",
  StringKeys.str_fortune: "قراءة الطالع",
  StringKeys.str_img: "صورة",
  StringKeys.str_response: "استجابة",
  StringKeys.str_profile: "الملف الشخصي",
  StringKeys.str_read: "اقرأ",
  StringKeys.str_country: "بلد",
  StringKeys.str_mobile: "رقم الهاتف الجوال",
  StringKeys.str_offline: "غير متصل على الانترنت",
  StringKeys.str_online: "عبر الانترنت",
  StringKeys.str_busy: "مشغول",
  StringKeys.str_away: "بعيدا",
  StringKeys.str_voice_response: "استجابة صوتية",
  StringKeys.str_buy_gold: "اشتري ذهبا",
  StringKeys.str_ability: "تغيير قدرتك",
  StringKeys.str_price: "أدخل سعرك",
  StringKeys.str_live_call: "مكالم\nمباشرة",
  StringKeys.str_voice_info: "هل تريد إنهاء التسجيل أم الإيقاف المؤقت؟",
  StringKeys.str_voice_pause: "يوقف",
  StringKeys.str_voice_stop: "قف",
  StringKeys.str_not_selected_image: "تحتاج إلى تحديد صورة واحدة على الأقل!",
  StringKeys.str_required_forename: "الاسم الأول مطلوب!",
  StringKeys.str_required_birt_place: "مكان التراب مطلوب!",
  StringKeys.str_required_sex: "المعلومات الجنسية المطلوبة!",
  StringKeys.str_required_social: "مطلوب معلومات الوضع الاجتماعي!",
  StringKeys.str_required_birth_date: "تاريخ الميلاد مطلوب!",
  StringKeys.str_required_voice: "التسجيل الصوتي مطلوب!",
  StringKeys.str_required_mother_name: "اسم الأم مطلوب!",
  StringKeys.str_notify_me: "اعلمني",
  StringKeys.str_not_notify: "لا تخطرني",
  StringKeys.str_call_expert: "خبير الاتصال",
  StringKeys.str_incoming_call: "مكالمة واردة",
  StringKeys.str_answered: "أجاب",
  StringKeys.str_not_answered: "بلا جواب",
  StringKeys.str_rejected: "مرفوض",
  StringKeys.str_waiting: "انتظار",

};
